// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zjeehveubaqomzjzlxpr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpqZWVodmV1YmFxb216anpseHByIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ4NTcwNzksImV4cCI6MjA1MDQzMzA3OX0.3OUWnw8wu8ry9lkWcu_8Lv03Gr3ubpahziAppxCQrnY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);