name: Sync to Abhishek-Portfolio

on:
  push:
    branches:
      - main # Adjust this to the branch you want to track

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Showcase Repository
        uses: actions/checkout@v3

      - name: Set Up Git
        run: |
          git config --global user.name "Abhishek Kat"
          git config --global user.email "chotuabhi97@gmail.com"

      - name: Add Portfolio Repository as Remote
        run: git remote add portfolio https://Abhishekkat:${{ secrets.ABHISHEK_PORTFOLIO_TOKEN }}@github.com/Abhishekkat/Abhishek-Portfolio.git


      - name: Push Changes to Portfolio Repository
        run: |
          git push portfolio main --force
